/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 captain_ship_island.glb --transform
Files: captain_ship_island.glb [8.74MB] > captain_ship_island-transformed.glb [1.03MB] (88%)

Camera control now lives in <CameraRig />. This component only renders the
island, ship, characters, and the interactive tour markers.
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import PirateIsland from "@/assets/captain_ship_island-transformed.glb";
import Ship from "@/assets/ship_custom.glb";
import {
  Mesh,
  SkinnedMesh,
  LoopOnce,
  LoopRepeat,
  AnimationAction,
} from "three";
import { STOPS } from "@/data/portfolio";
import { HOME_DOCK } from "@/data/anchors";
import Marker from "@/components/tour/Marker";
import FloatingVessel from "@/components/env/FloatingVessel";
import { useVoyage } from "@/components/tour/useVoyage";

// Resting lift so the gentle bob never sinks the ship into the water/island.
const VESSEL = { lift: 1.5 };

// The crew's authored world position was [21.745, 12.545, 105.041] and the
// ship's was [2.278, 2.838, 98.04]. In the ship-centered vessel frame the crew
// sits at their difference, so they stand on the deck and sail/rock with it.
const SHIP_TO_CREW = {
  x: 21.745 - 2.278, // 19.467
  y: 15.545 - 2.838, // 9.707
  z: 105.041 - 98.04, // 7.001
};

export default function Model(props: any) {
  const group = React.useRef();
  const { scene, animations } = useGLTF(PirateIsland);
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { materials: shipMaterials } = useGLTF(Ship);

  const { actions, mixer } = useAnimations(animations, group);
  useEffect(() => {
    const idle = actions["Idle"];
    const wave = actions["Wave"];
    const sail = actions["Sword"] || actions["Walk"]; // "manning the deck" pose

    // Crossfade helper: fade out everything else, fade the target in.
    const play = (
      action: AnimationAction | null | undefined,
      opts: { once?: boolean } = {},
    ) => {
      if (!action) return;
      Object.values(actions).forEach((a) => {
        if (a && a !== action && a.isRunning()) a.fadeOut(0.4);
      });
      action.reset();
      action.setLoop(opts.once ? LoopOnce : LoopRepeat, Infinity as any);
      action.clampWhenFinished = !!opts.once;
      action.fadeIn(0.4).play();
    };

    // Greet with a wave, then idle.
    play(wave, { once: true });
    const onFinished = (e: { action: AnimationAction }) => {
      // After the greeting wave, settle to idle (only if we're docked).
      if (e.action === wave && useVoyage.getState().phase === "docked") {
        play(idle);
      }
    };
    mixer.addEventListener("finished", onFinished as any);

    // React to voyage phase: sail pose while moving, greet+idle on arrival.
    let prevPhase = useVoyage.getState().phase;
    const unsub = useVoyage.subscribe((s) => {
      if (s.phase === prevPhase) return;
      if (s.phase === "sailing") {
        play(sail);
      } else if (s.phase === "docked") {
        // Arrived — a quick wave hello, then idle (via onFinished).
        play(wave, { once: true });
      }
      prevPhase = s.phase;
    });

    return () => {
      mixer.removeEventListener("finished", onFinished as any);
      unsub();
    };
  }, [actions, mixer]);

  // Let every island/character mesh cast + receive soft shadows.
  useEffect(() => {
    clone.traverse((o: any) => {
      if (o.isMesh) {
        o.castShadow = true;
        o.receiveShadow = true;
      }
    });
  }, [clone]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        {/* The ship + its crew ride the swell AND sail between docks as one
            floating vessel. The vessel group's origin moves to the ship's live
            sail position; children are offset by the HOME dock so they sit at
            their authored spots at rest. The vessel owns all yaw (heading), so
            the ship mesh's local Y-rotation is removed to avoid double-turning. */}
        <FloatingVessel baseY={VESSEL.lift} intensity={0.5}>
          {/* Ship-centered frame: the vessel origin IS the ship, and the crew
              is placed relative to the ship so everything yaws/rocks together
              as the deck. Ship base y (2.838) is the local vertical offset. */}
          <mesh
            name="Ship_Large"
            geometry={(nodes.Ship_Large as Mesh).geometry}
            material={shipMaterials["Atlas.003"]}
            position={[0, 2.838, 0]}
            scale={4.983}
          />
          <group
            name="CharacterArmature"
            position={[SHIP_TO_CREW.x, SHIP_TO_CREW.y, SHIP_TO_CREW.z]}
            scale={3.733}
          >
            <primitive object={nodes.Root} />
          </group>
          <skinnedMesh
            name="Captain_Barbarossa_"
            geometry={(nodes.Captain_Barbarossa_ as Mesh).geometry}
            material={materials["Atlas.001"]}
            skeleton={(nodes.Captain_Barbarossa_ as SkinnedMesh).skeleton}
            position={[SHIP_TO_CREW.x, SHIP_TO_CREW.y, SHIP_TO_CREW.z]}
            scale={3.733}
          />
          <skinnedMesh
            name="Ernest"
            geometry={(nodes.Ernest as Mesh).geometry}
            material={materials["Atlas.001"]}
            skeleton={(nodes.Ernest as SkinnedMesh).skeleton}
            position={[SHIP_TO_CREW.x, SHIP_TO_CREW.y, SHIP_TO_CREW.z]}
            scale={3.733}
          />
        </FloatingVessel>
        <mesh
          name="barrel_plank009_Building_0"
          geometry={(nodes.barrel_plank009_Building_0 as Mesh).geometry}
          material={materials.Building}
          position={[-14.263, 5.015, -18.203]}
          rotation={[2.092, -0.618, 2.351]}
          scale={0.524}
        />
        <mesh
          name="Box754_environment_0"
          geometry={(nodes.Box754_environment_0 as Mesh).geometry}
          material={materials.environment}
          position={[-47.034, 1.344, 21.926]}
          rotation={[-1.518, -0.083, 1.222]}
        />
        <mesh
          name="Object022_Material_#61_0"
          geometry={(nodes["Object022_Material_#61_0"] as Mesh).geometry}
          material={materials.Material_61}
          position={[-10.326, 0.4, -0.836]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        {/* The baked flat Sea_sea_0 + Sky_sky_0 meshes are intentionally NOT
            rendered — the stylized <Ocean />, <Sky />, and scene fog replace
            them (that flat teal water + hard horizon seam is gone).
            The captain + Ernest now live inside <FloatingVessel /> above. */}

        {/* Interactive tour markers — one per point of interest. */}
        {STOPS.map((stop, i) => (
          <Marker key={stop.id} stop={stop} index={i} />
        ))}
      </group>
    </group>
  );
}

useGLTF.preload(PirateIsland);
useGLTF.preload(Ship);
