// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: Jan Esch (https://sketchfab.com/Njan)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/twinleaf-town-56c75ce036b2418e9469995f0e87a8c8
// Title: Twinleaf Town
// */
// "use client";
// import React, { useRef, useEffect } from "react";
// import { useGLTF, useAnimations } from "@react-three/drei";
// // import { useFrame, useThree } from "@react-three/fiber";
// import TownScene from "../../assets/pokeball_twinleaf_town.glb";
// import { a } from "@react-spring/three";
// import { LoopOnce } from "three";

// const PokeTown = (props: any) => {
//   const PokeTownRef = useRef();
//   const { nodes, materials, animations } = useGLTF(TownScene);
//   const { actions } = useAnimations(animations, PokeTownRef);

//   useEffect(() => {
//     if (actions) {
//       const animationAction = actions["Take 001"]; // Replace with the actual animation name
//       if (animationAction) {
//         animationAction.setLoop(LoopOnce, 1); // Play the animation once
//         animationAction.clampWhenFinished = true; // Clamp the last frame when finished
//         animationAction.play();

//         // Stop the animation once it's finished
//         // animationAction.(() => {
//         //   animationAction.stop();
//         // });
//       }
//     }
//   }, [actions]);

//   return (
//     <a.group ref={PokeTownRef} {...props}>
//       <a.group name="Sketchfab_Scene">
//         <a.group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
//           <a.group name="Twinleaf_Townfbx" rotation={[Math.PI / 2, 0, 0]}>
//             <a.group name="Object_2">
//               <a.group name="RootNode">
//                 <a.group
//                   name="House01"
//                   position={[60.892, 0, -81.644]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="House01_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.House01_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="House02"
//                   position={[-75.215, 0, -85.352]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="House02_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.House02_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost01"
//                   position={[68.602, 0, -140.32]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost01_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost01_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="Fence"
//                   position={[73.914, 5.204, -140.218]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="Fence_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.Fence_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="Tree01"
//                   position={[151.19, 0, -90.955]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_13" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree01_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree01_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group name="PokeballBottom" rotation={[-Math.PI / 2, 0, 0]}>
//                   <a.group name="Object_16" position={[0, 0, -236.028]}>
//                     <mesh
//                       name="PokeballBottom_Pokeball_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.PokeballBottom_Pokeball_mat_0.geometry}
//                       material={materials.Pokeball_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="PokeballTop"
//                   position={[0, 13.915, -213.138]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="PokeballTop_Pokeball_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.PokeballTop_Pokeball_mat_0.geometry}
//                     material={materials.Pokeball_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="Mailbox"
//                   position={[-34.601, 0, -57.218]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="Mailbox_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.Mailbox_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="Sign"
//                   position={[11.486, 0, -21.206]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="Sign_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.Sign_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="Tree02"
//                   position={[162.136, 0, -118.866]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_25" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree02_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree02_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="FencePost02"
//                   position={[72.372, 0, -140.32]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost02_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost02_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="House003"
//                   position={[-72.901, 0, 44.411]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="House003_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.House003_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="House004"
//                   position={[72.012, 0, 38.937]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="House004_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.House004_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="Mailbox001"
//                   position={[28.461, 0, 67.569]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="Mailbox001_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.Mailbox001_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="Flower"
//                   position={[-74.975, 0, -150.684]}
//                   rotation={[Math.PI, 0, -Math.PI]}
//                 >
//                   <a.group
//                     name="Object_36"
//                     position={[1.951, 4.486, -0.008]}
//                     rotation={[-Math.PI / 2, 0.159, 0]}
//                   >
//                     <mesh
//                       name="Flower_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Flower_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="FencePost003"
//                   position={[76.359, 0, -140.32]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost003_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost003_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost004"
//                   position={[80.129, 0, -140.32]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost004_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost004_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost005"
//                   position={[84.116, 0, -140.32]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost005_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost005_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost006"
//                   position={[87.886, 0, -140.32]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost006_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost006_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost007"
//                   position={[91.873, 0, -140.32]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost007_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost007_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost008"
//                   position={[95.643, 0, -140.32]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost008_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost008_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost009"
//                   position={[99.63, 0, -140.32]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost009_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost009_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost010"
//                   position={[103.4, 0, -140.32]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost010_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost010_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost011"
//                   position={[107.475, 0, -140.32]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost011_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost011_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost012"
//                   position={[111.245, 0, -140.32]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost012_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost012_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost013"
//                   position={[115.378, 0, -140.32]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost013_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost013_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost014"
//                   position={[108.087, 0, -173.726]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost014_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost014_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost015"
//                   position={[104.316, 0, -173.726]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost015_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost015_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost016"
//                   position={[100.33, 0, -173.726]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost016_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost016_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost017"
//                   position={[96.56, 0, -173.726]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost017_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost017_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost018"
//                   position={[92.573, 0, -173.726]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost018_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost018_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost019"
//                   position={[88.803, 0, -173.726]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost019_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost019_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost020"
//                   position={[84.816, 0, -173.726]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost020_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost020_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost021"
//                   position={[115.843, 0, -173.726]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost021_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost021_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost022"
//                   position={[81.046, 0, -173.726]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost022_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost022_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost023"
//                   position={[76.97, 0, -173.726]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost023_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost023_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost024"
//                   position={[73.2, 0, -173.726]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost024_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost024_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost025"
//                   position={[69.068, 0, -173.726]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost025_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost025_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost026"
//                   position={[112.073, 0, -173.726]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost026_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost026_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost027"
//                   position={[118.39, 0, -151.647]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost027_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost027_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost028"
//                   position={[118.39, 0, -147.876]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost028_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost028_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost029"
//                   position={[118.39, 0, -143.89]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost029_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost029_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost030"
//                   position={[66.506, 0, -143.269]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost030_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost030_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost031"
//                   position={[66.506, 0, -147.256]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost031_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost031_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost032"
//                   position={[66.506, 0, -151.026]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost032_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost032_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost033"
//                   position={[66.506, 0, -155.013]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost033_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost033_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost034"
//                   position={[118.39, 0, -159.403]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost034_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost034_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost035"
//                   position={[66.506, 0, -158.783]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost035_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost035_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost036"
//                   position={[66.506, 0, -162.859]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost036_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost036_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost037"
//                   position={[66.506, 0, -166.629]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost037_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost037_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost038"
//                   position={[66.506, 0, -170.761]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost038_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost038_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost039"
//                   position={[118.39, 0, -155.633]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost039_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost039_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost040"
//                   position={[118.39, 0, -170.841]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost040_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost040_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost041"
//                   position={[118.39, 0, -167.071]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost041_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost041_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost042"
//                   position={[118.39, 0, -163.084]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost042_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost042_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="Fence001"
//                   position={[-76.068, 5.204, -173.952]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="Fence001_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.Fence001_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost043"
//                   position={[-78.514, 0, -173.849]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost043_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost043_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost044"
//                   position={[-82.284, 0, -173.849]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost044_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost044_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost045"
//                   position={[-86.271, 0, -173.849]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost045_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost045_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost046"
//                   position={[-90.041, 0, -173.849]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost046_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost046_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost047"
//                   position={[-94.028, 0, -173.849]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost047_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost047_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost048"
//                   position={[-97.798, 0, -173.849]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost048_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost048_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost049"
//                   position={[-101.785, 0, -173.849]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost049_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost049_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost050"
//                   position={[-70.757, 0, -173.849]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost050_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost050_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost051"
//                   position={[-105.555, 0, -173.849]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost051_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost051_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost052"
//                   position={[-109.63, 0, -173.849]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost052_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost052_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost053"
//                   position={[-113.4, 0, -173.849]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost053_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost053_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost054"
//                   position={[-117.533, 0, -173.849]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost054_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost054_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost055"
//                   position={[-110.241, 0, -140.444]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost055_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost055_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost056"
//                   position={[-106.471, 0, -140.444]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost056_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost056_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost057"
//                   position={[-102.485, 0, -140.444]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost057_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost057_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost058"
//                   position={[-98.714, 0, -140.444]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost058_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost058_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost059"
//                   position={[-94.728, 0, -140.444]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost059_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost059_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost060"
//                   position={[-90.958, 0, -140.444]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost060_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost060_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost061"
//                   position={[-74.527, 0, -173.849]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <mesh
//                     name="FencePost061_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost061_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost062"
//                   position={[-86.971, 0, -140.444]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost062_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost062_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost063"
//                   position={[-117.998, 0, -140.444]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost063_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost063_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost064"
//                   position={[-83.201, 0, -140.444]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost064_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost064_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost065"
//                   position={[-79.125, 0, -140.444]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost065_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost065_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost066"
//                   position={[-75.355, 0, -140.444]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost066_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost066_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost067"
//                   position={[-71.223, 0, -140.444]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost067_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost067_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost068"
//                   position={[-114.228, 0, -140.444]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI]}
//                 >
//                   <mesh
//                     name="FencePost068_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost068_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost069"
//                   position={[-120.545, 0, -162.523]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost069_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost069_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost070"
//                   position={[-120.545, 0, -166.293]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost070_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost070_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost071"
//                   position={[-120.545, 0, -170.28]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost071_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost071_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost072"
//                   position={[-68.66, 0, -170.9]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost072_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost072_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost073"
//                   position={[-68.66, 0, -166.914]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost073_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost073_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost074"
//                   position={[-68.66, 0, -163.144]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost074_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost074_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost075"
//                   position={[-68.66, 0, -159.157]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost075_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost075_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost076"
//                   position={[-120.545, 0, -154.766]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost076_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost076_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost077"
//                   position={[-68.66, 0, -155.387]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost077_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost077_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost078"
//                   position={[-68.66, 0, -151.311]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost078_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost078_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost079"
//                   position={[-68.66, 0, -147.541]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost079_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost079_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost080"
//                   position={[-68.66, 0, -143.409]}
//                   rotation={[-Math.PI / 2, 0, Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost080_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost080_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost081"
//                   position={[-120.545, 0, -158.537]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost081_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost081_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost082"
//                   position={[-120.545, 0, -143.329]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost082_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost082_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost083"
//                   position={[-120.545, 0, -147.099]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost083_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost083_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="FencePost084"
//                   position={[-120.545, 0, -151.086]}
//                   rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//                 >
//                   <mesh
//                     name="FencePost084_Town_mat_0"
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.FencePost084_Town_mat_0.geometry}
//                     material={materials.Town_mat}
//                   />
//                 </a.group>
//                 <a.group
//                   name="Flower001"
//                   position={[-84.742, 0, -150.629]}
//                   rotation={[Math.PI, 0, -Math.PI]}
//                 >
//                   <a.group
//                     name="Object_205"
//                     position={[1.951, 4.486, -0.008]}
//                     rotation={[-Math.PI / 2, 0.159, 0]}
//                   >
//                     <mesh
//                       name="Flower001_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Flower001_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Flower002"
//                   position={[-95.036, 0, -150.574]}
//                   rotation={[Math.PI, 0, -Math.PI]}
//                 >
//                   <a.group
//                     name="Object_208"
//                     position={[1.951, 4.486, -0.008]}
//                     rotation={[-Math.PI / 2, 0.159, 0]}
//                   >
//                     <mesh
//                       name="Flower002_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Flower002_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Flower003"
//                   position={[-74.975, 0, -164.502]}
//                   rotation={[Math.PI, 0, -Math.PI]}
//                 >
//                   <a.group
//                     name="Object_211"
//                     position={[1.951, 4.486, -0.008]}
//                     rotation={[-Math.PI / 2, 0.159, 0]}
//                   >
//                     <mesh
//                       name="Flower003_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Flower003_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Flower004"
//                   position={[-94.049, 0, -164.502]}
//                   rotation={[Math.PI, 0, -Math.PI]}
//                 >
//                   <a.group
//                     name="Object_214"
//                     position={[1.951, 4.486, -0.008]}
//                     rotation={[-Math.PI / 2, 0.159, 0]}
//                   >
//                     <mesh
//                       name="Flower004_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Flower004_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Flower005"
//                   position={[-103.086, 0, -164.502]}
//                   rotation={[Math.PI, 0, -Math.PI]}
//                 >
//                   <a.group
//                     name="Object_217"
//                     position={[1.951, 4.486, -0.008]}
//                     rotation={[-Math.PI / 2, 0.159, 0]}
//                   >
//                     <mesh
//                       name="Flower005_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Flower005_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree003"
//                   position={[133.016, 0, -152.645]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_220" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree003_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree003_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree004"
//                   position={[136.114, 0, -124.713]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_223" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree004_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree004_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree005"
//                   position={[158.777, 0, -61.341]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_226" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree005_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree005_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree006"
//                   position={[189.795, 0, -30.443]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_229" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree006_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree006_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree007"
//                   position={[189.795, 0, 0.454]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_232" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree007_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree007_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree008"
//                   position={[158.777, 0, 31.352]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_235" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree008_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree008_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree009"
//                   position={[158.777, 0, 62.249]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_238" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree009_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree009_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree010"
//                   position={[174.458, 0, 94.006]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_241" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree010_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree010_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree011"
//                   position={[186.939, 0, 63.508]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_244" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree011_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree011_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree012"
//                   position={[189.123, 0, 32.125]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_247" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree012_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree012_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree013"
//                   position={[157.323, 0, 122.405]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_250" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree013_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree013_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree014"
//                   position={[138.019, 0, 146.387]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_253" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree014_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree014_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree015"
//                   position={[160.377, 0, -31.054]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_256" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree015_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree015_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree016"
//                   position={[159.122, 0, 1.727]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_259" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree016_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree016_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree017"
//                   position={[189.542, 0, -60.44]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_262" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree017_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree017_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree018"
//                   position={[180.277, 0, -88.901]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_265" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree018_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree018_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree019"
//                   position={[112.932, 0, 165.817]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_268" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree019_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree019_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree020"
//                   position={[84.156, 0, 175.634]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_271" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree020_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree020_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree021"
//                   position={[90.449, 0, 146.098]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_274" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree021_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree021_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree022"
//                   position={[125.735, 0, 121.103]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_277" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree022_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree022_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree023"
//                   position={[145.626, 0, 93.114]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_280" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree023_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree023_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree024"
//                   position={[65.139, 0, -187.697]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_283" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree024_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree024_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree025"
//                   position={[37.027, 0, -194.845]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_286" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree025_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree025_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree026"
//                   position={[-32.484, 0, -197.072]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_289" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree026_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree026_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree027"
//                   position={[-62.053, 0, -187.758]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_292" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree027_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree027_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree028"
//                   position={[-137.662, 0, -145.361]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_295" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree028_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree028_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree029"
//                   position={[-137.662, 0, -116.132]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_298" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree029_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree029_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree030"
//                   position={[-177.105, 0, -86.131]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_301" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree030_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree030_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree031"
//                   position={[-185.281, 0, -55.499]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_304" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree031_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree031_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree032"
//                   position={[-155.946, 0, -59.514]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_307" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree032_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree032_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree033"
//                   position={[-192.701, 0, 3.851]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_310" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree033_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree033_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree034"
//                   position={[-163.442, 0, 24.321]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_313" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree034_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree034_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree035"
//                   position={[-135.495, 0, 104.511]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_316" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree035_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree035_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree036"
//                   position={[-163.016, 0, -114.87]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_319" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree036_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree036_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree038"
//                   position={[-90.801, 0, 147.711]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_322" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree038_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree038_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree039"
//                   position={[-114.882, 0, 163.702]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_325" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree039_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree039_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree040"
//                   position={[-146.589, 0, -87.962]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_328" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree040_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree040_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree041"
//                   position={[-171.348, 0, 102.539]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_331" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree041_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree041_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree042"
//                   position={[-191.299, 0, -27.568]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_334" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree042_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree042_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree043"
//                   position={[-161.354, 0, -34.564]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_337" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree043_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree043_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree044"
//                   position={[-164.177, 0, -5.596]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_340" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree044_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree044_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree045"
//                   position={[-189.638, 0, 38.496]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_343" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree045_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree045_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree046"
//                   position={[-159.203, 0, 53.009]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_346" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree046_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree046_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree047"
//                   position={[-182.013, 0, 73.622]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_349" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree047_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree047_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree048"
//                   position={[-150.287, 0, 81.483]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_352" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree048_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree048_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree049"
//                   position={[-156.494, 0, 125.019]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_355" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree049_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree049_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree050"
//                   position={[-114.992, 0, 130.831]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_358" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree050_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree050_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree051"
//                   position={[-139, 0, 146.445]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_361" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree051_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree051_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//                 <a.group
//                   name="Tree052"
//                   position={[-80.729, 0, 175.159]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                 >
//                   <a.group name="Object_364" position={[0, 0, 0.123]}>
//                     <mesh
//                       name="Tree052_Town_mat_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Tree052_Town_mat_0.geometry}
//                       material={materials.Town_mat}
//                     />
//                   </a.group>
//                 </a.group>
//               </a.group>
//             </a.group>
//           </a.group>
//         </a.group>
//       </a.group>
//     </a.group>
//   );
// };

// // useGLTF.preload("/pokeball_twinleaf_town.glb");
// export default PokeTown;
