// GENERATED by blender/export_world.py from blender/world.py. Do not edit:
// move a prop or an NPC in Blender and re-export.

export interface Shot {
  position: [number, number, number];
  target: [number, number, number];
}

/**
 * The camera's close-up for each clickable thing: "poi:<key>" for a prop
 * (framed from its real bounds), "npc:<key>" for a character (3/4, eye level).
 */
export const SHOTS: Record<string, Shot> = {
  "poi:intro": {
    "position": [
      19.127,
      6.594,
      74.052
    ],
    "target": [
      14.985,
      4.84,
      66.914
    ]
  },
  "poi:projects_0": {
    "position": [
      -273.186,
      16.711,
      -92.825
    ],
    "target": [
      -282.467,
      14.236,
      -99.856
    ]
  },
  "poi:projects_1": {
    "position": [
      -265.523,
      10.573,
      -90.493
    ],
    "target": [
      -270.0,
      9.364,
      -94.0
    ]
  },
  "poi:projects_2": {
    "position": [
      -250.235,
      11.202,
      -86.183
    ],
    "target": [
      -256.917,
      9.329,
      -91.929
    ]
  },
  "poi:projects_3": {
    "position": [
      -241.941,
      5.977,
      -96.203
    ],
    "target": [
      -244.882,
      5.074,
      -99.268
    ]
  },
  "poi:resume": {
    "position": [
      232.962,
      2.721,
      180.067
    ],
    "target": [
      235.76,
      1.464,
      174.857
    ]
  },
  "poi:experience": {
    "position": [
      198.866,
      48.453,
      -272.538
    ],
    "target": [
      196.0,
      45.942,
      -284.0
    ]
  },
  "poi:contact": {
    "position": [
      -226.322,
      52.021,
      239.817
    ],
    "target": [
      -227.981,
      51.134,
      235.984
    ]
  },
  "npc:anne": {
    "position": [
      16.456,
      3.945,
      74.204
    ],
    "target": [
      10.5,
      2.045,
      69.5
    ]
  },
  "npc:henry": {
    "position": [
      -256.834,
      10.235,
      -85.5
    ],
    "target": [
      -264.0,
      8.335,
      -88.0
    ]
  },
  "npc:skeleton": {
    "position": [
      233.946,
      3.649,
      177.783
    ],
    "target": [
      235.059,
      1.749,
      170.275
    ]
  },
  "npc:mako": {
    "position": [
      196.27,
      38.619,
      -272.726
    ],
    "target": [
      192.0,
      36.719,
      -279.0
    ]
  },
  "npc:sharky": {
    "position": [
      -226.751,
      52.075,
      244.481
    ],
    "target": [
      -232.0,
      50.175,
      239.0
    ]
  }
};

/** Where each NPC stands. `yaw` is rotation.y; `scale` makes them 1.8 m tall. */
export const NPC_PLACEMENTS: Record<string, { file: string; position: [number, number, number]; yaw: number; scale: number }> = {
  "anne": {
    "file": "Characters_Anne.gltf",
    "position": [
      10.5,
      1.345,
      69.5
    ],
    "yaw": 0.5806,
    "scale": 1.172
  },
  "henry": {
    "file": "Characters_Henry.gltf",
    "position": [
      -264.0,
      7.635,
      -88.0
    ],
    "yaw": 0.9134,
    "scale": 1.1945
  },
  "skeleton": {
    "file": "Characters_Skeleton.gltf",
    "position": [
      235.059,
      1.049,
      170.275
    ],
    "yaw": -0.469,
    "scale": 1.2806
  },
  "mako": {
    "file": "Characters_Mako.gltf",
    "position": [
      192.0,
      36.019,
      -279.0
    ],
    "yaw": 0.2758,
    "scale": 1.1009
  },
  "sharky": {
    "file": "Characters_Sharky.gltf",
    "position": [
      -232.0,
      49.475,
      239.0
    ],
    "yaw": 0.442,
    "scale": 1.2413
  }
};

/** Where the original animated treasure chest stands (Skull Cove). */
export const CHEST_PLACEMENT = {
  "position": [
    235.772,
    0.5,
    174.829
  ],
  "yaw": -0.4929
};
