// -----------------------------------------------------------------------------
// INTERACTION WIRING: what every clickable thing in the world does.
//
// Content stays in portfolio.ts. This file maps the props in the world GLB
// (nodes named POI_*, built in blender/lib/poi.py) and the NPCs
// (blender/lib/npc.py) onto tour stops and sub-POIs, and holds the NPCs' lines.
// Camera close-ups come from interactables.ts, generated by the Blender export.
// -----------------------------------------------------------------------------

import { STOPS } from "./portfolio";

export interface Interactable {
  /** Stable key: "poi:<name>" or "npc:<name>". */
  key: string;
  kind: "poi" | "npc";
  /** Hand-lettered tag shown on hover. */
  tag: string;
  /** Close-up to fly to (a key of SHOTS in interactables.ts). */
  shot: string;
  /** Tour stop this belongs to (portfolio.ts id). */
  stopId: string;
  /** Index into that stop's subPois, or null for the stop itself. */
  subPoi: number | null;
}

const stop = (id: string) => STOPS.find((s) => s.id === id);
const subLabel = (id: string, i: number) => stop(id)?.subPois?.[i]?.label ?? "";

/** World-GLB prop node -> what it is. Child parts resolve to their prop. */
export const PROPS: Record<string, Interactable> = {
  POI_intro: { key: "poi:intro", kind: "poi", tag: "Wanted: The Captain", shot: "poi:intro", stopId: "intro", subPoi: null },
  POI_resume: { key: "poi:resume", kind: "poi", tag: "Treasure Chest · Résumé", shot: "poi:resume", stopId: "resume", subPoi: null },
  POI_experience: { key: "poi:experience", kind: "poi", tag: "Signal Flags · Experience", shot: "poi:experience", stopId: "experience", subPoi: null },
  POI_contact: { key: "poi:contact", kind: "poi", tag: "Message in a Bottle", shot: "poi:contact", stopId: "contact", subPoi: null },
};
for (let i = 0; i < 4; i++) {
  PROPS[`POI_projects_${i}`] = {
    key: `poi:projects_${i}`,
    kind: "poi",
    tag: subLabel("project-1", i),
    shot: `poi:projects_${i}`,
    stopId: "project-1",
    subPoi: i,
  };
  PROPS[`POI_experience_${i}`] = {
    key: `poi:experience_${i}`,
    kind: "poi",
    tag: subLabel("experience", i),
    shot: "poi:experience",
    stopId: "experience",
    subPoi: i,
  };
}

/** The prop a GLB node belongs to: itself, or its nearest named ancestor. */
export function propFor(nodeNames: string[]): Interactable | null {
  for (const n of nodeNames) if (PROPS[n]) return PROPS[n];
  return null;
}

/** Sub-POI index -> the prop that shows it (for the NPCs' choices). */
export function propForSubPoi(stopId: string, index: number): Interactable | null {
  return Object.values(PROPS).find((p) => p.stopId === stopId && p.subPoi === index) ?? null;
}

// -----------------------------------------------------------------------------
// NPCs
// -----------------------------------------------------------------------------

export type DialogueAction =
  | { type: "stop"; stopId: string } // open the stop's panel (sails there if needed)
  | { type: "sub"; stopId: string; index: number } // open a sub-POI via its prop
  | { type: "sail"; stopId: string } // just go there
  | { type: "home" } // back to home port
  | { type: "close" };

export interface Npc extends Interactable {
  name: string;
  role: string;
  lines: string[];
  /** Said instead of `lines` when you come back to them. */
  again: string;
  options: { label: string; action: DialogueAction }[];
}

const subOptions = (stopId: string) =>
  (stop(stopId)?.subPois ?? []).map((p, index) => ({
    label: p.label,
    action: { type: "sub", stopId, index } as DialogueAction,
  }));

const npc = (key: string, stopId: string, name: string, role: string, lines: string[],
  options: Npc["options"], again = "Anything else?"): Npc => ({
  key: `npc:${key}`,
  kind: "npc",
  tag: `${name} · ${role}`,
  shot: `npc:${key}`,
  stopId,
  subPoi: null,
  name,
  role,
  lines,
  again,
  options,
});

export const NPCS: Record<string, Npc> = {
  // At the ship's wheel; he goes wherever the ship goes, so no stop and no
  // close-up of his own: talking to him is another way to navigate.
  captain: {
    ...npc("captain", "", "Captain Barbarossa", "At the Helm", [
      "Arr, the wind's fair and the rum's mostly water. Where to next?",
    ], [
      ...STOPS.filter((s) => s.id !== "intro").map((s) => ({
        label: s.label,
        action: { type: "sail", stopId: s.id } as DialogueAction,
      })),
      { label: "Home port", action: { type: "home" } },
    ], "Where to next, then?"),
    shot: "",
  },
  anne: npc("anne", "intro", "Anne", "Harbourmaster", [
    "Ahoy, and welcome to port! That scoundrel on the poster? That's our captain.",
    "Four islands out there, each holding a piece of their story. Where'll it be?",
  ], [
    { label: "Tell me about the captain", action: { type: "stop", stopId: "intro" } },
    { label: "Their projects (Ember Isle)", action: { type: "sail", stopId: "project-1" } },
    { label: "Their voyages (Lighthouse Rock)", action: { type: "sail", stopId: "experience" } },
    { label: "Their résumé (Skull Cove)", action: { type: "sail", stopId: "resume" } },
    { label: "Send word (Drifting Isle)", action: { type: "sail", stopId: "contact" } },
  ], "Back already? Where to next?"),
  henry: npc("henry", "project-1", "Henry", "Tinkerer", [
    "Mind the lava, it's warm this time of year.",
    "Every contraption in this camp is one of the captain's builds. Pick one and I'll tell you how it ticks.",
  ], subOptions("project-1"), "Another contraption? Take your pick."),
  skeleton: npc("skeleton", "resume", "Old Bones", "Chest Guard", [
    "Dead men tell no tales...",
    "...but this chest does. The captain's whole record's in there. Help yourself, it's the only treasure I'm allowed to give away.",
  ], [
    { label: "Open the chest", action: { type: "stop", stopId: "resume" } },
  ], "Still here? So am I. Always."),
  mako: npc("mako", "experience", "Mako", "Lighthouse Keeper", [
    "Each of those flags is a crew the captain sailed with. Oldest on the left, newest on the right.",
    "Pick a flag and I'll tell you what they did aboard.",
  ], subOptions("experience"), "Another flag, then?"),
  sharky: npc("sharky", "contact", "Sharky", "Messenger", [
    "Got something to say to the captain? Put it in a bottle and I'll swim it over.",
    "Fastest fins on the Drifting Isle. Well, only fins.",
  ], [
    { label: "Write a message", action: { type: "stop", stopId: "contact" } },
  ], "Changed your mind? Fins are still fast."),
};

/** The NPC who hosts a stop and greets you on arrival (never the captain). */
export function hostOf(stopId: string): string | null {
  const hit = Object.entries(NPCS).find(([id, n]) => id !== "captain" && n.stopId === stopId);
  return hit ? hit[0] : null;
}
