// GENERATED by blender/export_world.py from blender/lib/stage.py and
// blender/lib/materials.py. Do not edit by hand: change the Blender side and
// re-export, so the app and the approved renders keep the same light.

/** Direction TO the key light (three.js world space, normalised). */
export const KEY_DIR: [number, number, number] = [-0.96329, 0.20791, 0.16985];
/** Direction TO the visible sun disc in the sky panorama. */
export const SUN_DISC_DIR: [number, number, number] = [-0.98106, 0.08716, 0.17299];
/** Key light colour (linear) and intensity (same units as Blender's sun strength). */
export const KEY_COLOR: [number, number, number] = [1.0, 0.64, 0.36];
export const KEY_INTENSITY = 6.5;

/** Distance haze, FogExp2 curve, colour in linear working space. */
export const FOG_COLOR: [number, number, number] = [0.3, 0.36, 0.48];
export const FOG_DENSITY = 0.0011;

/** Sky panorama (HDR, already at the approved strength) and shore field. */
export const SKY_URL = "/world/sky.hdr";
export const SHORE_URL = "/world/shore.png";
/** The shore map spans [-EXTENT, EXTENT] metres on world X and Z. */
export const SHORE_EXTENT = 512.0;
/** A texel value of 1.0 means this many metres (or more) from any shoreline. */
export const SHORE_MAX = 96.0;
